import { FormValueInterface } from "../../core/models/fast-subscription-Interface.models"

export const initialValues: FormValueInterface = {
  firstName: "",
  lastName: "",
  cellphone: "",
  username: "",
  email: "",
  password: "",
  repassword: "",
  gender: 0,
  dayOfBirthDate: 0,
  monthOfBirthDate: 0,
  yearOfBirthDate: 0,
  languageId1: 0,
  languageId2: 0,
  languageId3: 0,
  locationId: 0,
  locationId2: 0,
  locationId3: 0,
  locationTitle: "",
  mainInstrument: 0,
  mainStartingDate: 0,
  mainLevel: 0,
  mainStyle1: 0,
  mainStyle2: 0,
  mainStyle3: 0,
  secondInstrument: 0,
  secondStartingDate: 0,
  secondLevel: 0,
  secondStyle1: 0,
  secondStyle2: 0,
  secondStyle3: 0,
  howKnowingUs: "",
  reference: "",
}
